---
# Mise
mise_version: "v2026.3.9"

# App Packages
apt_packages:
  - wezterm
  - zsh

# Fonts
jetbrains_mono_version: "3.4.0"

# Dotfiles
dotfiles_repo: "https://github.com/benpops89/dotfiles.git"
dotfiles_dir: "{{ ansible_user_dir }}/dotfiles"

dotfiles_symlinks:
  - .zshrc
  - .zshenv
  - .config/opencode
  - .config/nvim
  - .config/starship.toml
  - .config/tmux
  - .config/lazygit

# Users in the docker group
docker_users:
  - demo
