---
# Mise
mise_version: "v2026.3.13"
mise_sha256: "sha256:583bed85629f1f3583adcd07eb47ef2cfe94e88d5de30f4e1a5278f3a123b614"

# App Packages
apt_packages:
  - wezterm
  - zsh

# Fonts
jetbrains_mono_version: "3.4.0"
jetbrains_mono_sha256: "sha256:76f05ff3ace48a464a6ca57977998784ff7bdbb65a6d915d7e401cd3927c493c"

# Dotfiles
dotfiles_repo: "https://github.com/benpops89/demo-dots.git"
dotfiles_dir: "{{ ansible_user_dir }}/dotfiles"

dotfiles_symlinks:
  - .zshrc
  - .zshenv
  - .config/opencode
  - .config/nvim
  - .config/starship.toml
  - .config/tmux
  - .config/lazygit
  - .config/sheldon
  - .config/wezterm
  - .config/mise

# Users in the docker group
docker_users:
  - demo
