---
# Mise
mise_version: "v2026.3.9"
mise_sha256: "sha256:5302866459744a7bad872d7dccdc5e2cf5d32e80c46f142c805cc21c94dfb6ad"

# App Packages
apt_packages:
  - wezterm
  - zsh

# Fonts
jetbrains_mono_version: "3.4.0"

# Dotfiles
dotfiles_repo: "https://github.com/benpops89/demo-dots.git"
dotfiles_dir: "{{ ansible_user_dir }}/dotfiles"

dotfiles_symlinks:
  - .zshrc
  - .zshenv
  - .config/opencode
  - .config/nvim
  - .config/starship.toml
  - .config/tmux
  - .config/lazygit
  - .config/sheldon
  - .config/wezterm

# Users in the docker group
docker_users:
  - demo
