---
- name: Demo Playbook
  hosts: localhost
  connection: local

  vars_files:
    - config.yml

  roles:
    - role: geerlingguy.docker
      become: true

  tasks:
    - name: Include APT tasks
      ansible.builtin.import_tasks: tasks/apt.yml

    - name: Include fonts tasks
      ansible.builtin.import_tasks: tasks/fonts.yml

    - name: Set default shell to zsh
      ansible.builtin.user:
        name: "{{ ansible_user_id }}"
        shell: /usr/bin/zsh
      become: true

    - name: Include dotfiles tasks
      ansible.builtin.import_tasks: tasks/dotfiles.yml

    - name: Include mise tasks
      ansible.builtin.import_tasks: tasks/mise.yml

  handlers:
    - name: Rebuild font cache
      ansible.builtin.command: fc-cache -fv
