---
- name: Create fonts directory
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.local/share/fonts/JetBrainsMono"
    state: directory
    mode: '0755'

- name: Download JetBrains Mono Nerd Font
  ansible.builtin.get_url:
    url: "https://github.com/ryanoasis/nerd-fonts/releases/download/v{{ jetbrains_mono_version }}/JetBrainsMono.zip"
    dest: "{{ ansible_user_dir }}/.local/share/fonts/JetBrainsMono.zip"
    mode: '0644'
    checksum: "{{ jetbrains_mono_sha256 }}"

- name: Check if JetBrains Mono fonts are extracted
  ansible.builtin.find:
    paths: "{{ ansible_user_dir }}/.local/share/fonts/JetBrainsMono"
    file_type: file
  register: jetbrains_fonts_files

- name: Extract JetBrains Mono Nerd Font
  ansible.builtin.unarchive:
    src: "{{ ansible_user_dir }}/.local/share/fonts/JetBrainsMono.zip"
    dest: "{{ ansible_user_dir }}/.local/share/fonts/JetBrainsMono"
    remote_src: yes
  notify: Rebuild font cache
  when: jetbrains_fonts_files.files | length == 0
